---
apiVersion: mount.vault.jet.crossplane.io/v1alpha1
kind: Mount
metadata:
  name: "pki-example"
spec:
  forProvider:
    path: "pki-example"
    type: "pki"
    description: "This is an example PKI mount"
    defaultLeaseTtlSeconds: 3600
    maxLeaseTtlSeconds: 86400
---
apiVersion: pki.vault.jet.crossplane.io/v1alpha1
kind: SecretBackendConfigUrls
metadata:
  name: "pki-example-config-urls"
spec:
  forProvider:
    issuingCertificates: 
     - "http://127.0.0.1:8200/v1/pki-example/ca"
    backendRef:
      name: pki-example
---
apiVersion: pki.vault.jet.crossplane.io/v1alpha1
kind: SecretBackendRootCert
metadata:
  name: "pki-example-root-cert"
spec:
  forProvider:
    commonName: "Root CA"
    type: "internal"
    backendRef:
      name: pki-example
---
apiVersion: pki.vault.jet.crossplane.io/v1alpha1
kind: SecretBackendRole
metadata:
  name: "pki-example-role"
spec:
  forProvider:
    name: "my_role"
    ttl: "3600"
    allowIpSans: true
    keyType: "rsa"
    keyBits: 4096
    allowedDomains: ["example.com", "my.domain"]
    allowSubdomains: true
    backendRef:
      name: pki-example


